---
abstract: 'Simple file triple and quad store based on NTriple files.'
author:
  - 'Kjetil Kjernsmo <kjetilk@cpan.org>'
build_requires:
  Test::More: 0
  Test::RDF: 0.24
  Test::RDF::Trine::Store: 0.137
  URI::Escape: 0
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.023, CPAN::Meta::Converter version 2.133380'
keywords:
  - 'Semantic Web'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RDF-Trine-Store-File
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  RDF::Trine::Store::File:
    file: lib/RDF/Trine/Store/File.pm
    version: 0.11_2
  RDF::Trine::Store::File::Quad:
    file: lib/RDF/Trine/Store/File/Quad.pm
requires:
  Carp: 0
  Digest::MD5: 0
  File::Data: 0
  File::Temp: 0
  File::Util: 0
  List::MoreUtils: 0
  Log::Log4perl: 0
  RDF::Trine: 1.011
  Scalar::Util: 0
resources:
  IRC: irc://irc.perl.org/#perlrdf
  Identifier: http://purl.org/NET/cpan-uri/dist/RDF-Trine-Store-File/project
  Mailinglist: http://lists.perlrdf.org/listinfo/dev
  Wiki: http://wiki.perlrdf.org/
  bugtracker: https://github.com/kjetilk/RDF-Trine-Store-File/issues
  homepage: https://metacpan.org/release/RDF-Trine-Store-File
  license: http://dev.perl.org/licenses/
  repository: https://github.com/kjetilk/RDF-Trine-Store-File/
version: 0.11_2
