---
abstract: 'Using a file with N-Triples as triplestore'
author:
  - 'Kjetil Kjernsmo, C<< <kjetilk at cpan.org> >>'
  - 'Kjetil Kjernsmo <kjetilk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  Test::RDF: 0.24
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.02'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RDF-Trine-Store-File
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  Digest::MD5: 0
  File::Data: 0
  File::Temp: 0
  File::Util: 0
  Log::Log4perl: 0
  RDF::Trine: 0
  Scalar::Util: 0
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=RDF-Trine-Store-File
  license: http://dev.perl.org/licenses/
  repository: git://github.com/kjetilk/RDF-Trine-Store-File.git
version: 0.02
